package com.hellokoding.springboot.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
@Entity
@Table(name = "news")
public class News {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  @NotNull
  private String title;
  
  @NotNull
  private String content;

  // Public methods
  
  public News() { }

  public News(long id) { 
    this.id = id;
  }
  
  public News(String title, String content) {
    this.title = title;
    this.content = content;
  }

  // Getter and setter methods
  // ...

}
